### ISSUE TITLE
Hello world contract for the landing page of https://docs.tact-lang.org

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#100]
Many languages give the programmer a taste of a simple program right off-the-bat, we should do the same

**Comment by novusnota** [comment]
Well, the https://tact-lang.org kinda does it already, while starting page of the docs helps to quickly setup people's first contract with the help of Blueprint. And I personally wouldn't want to move "Let's start!" down this page just to make sure that it's clear and accessible right away.

But maybe a hello world / counter contract would make sense [here](https://docs.tact-lang.org/#thats-it-your-first-contract-project-is-written-and-compiled-already), just to showcase the code of a newly deployed contract

**Comment by anton-trunov** [comment]
Showing that contract code after we have said how to generate/set it up would be definitely useful
