### ISSUE TITLE
Exit codes page does not allow precise links for each individual exit code

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#101]

**Comment by novusnota** [comment]
Depends on #106

**Comment by novusnota** [comment]
> I think this is resolved now. Is it true @novusnota? E.g. https://docs.tact-lang.org/book/exit-codes#4

Yes, the initial issue is resolved, so I'll close this. However, the need in re-writing the that page as per #106 still stands, such that all exit codes would have precise links
