### ISSUE TITLE
Add a link to exit code 5 in book/integers.mdx (for storage overflow explanation)

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#107]
Once #101 is resolved

**Comment by novusnota** [comment]
Added the temporary link to the TON docs in #97, until we have our own page in #106

**Comment by novusnota** [comment]
Will be resolved before the pages gets a complete re-write in #106, because I've cleaned up it a little and placed into the Book. Soon I'll push a relevant PR :)
