### ISSUE TITLE
Docs need a "Structure of a Contract" page

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#115]
Similar to what Solidity (https://docs.soliditylang.org/en/v0.8.25/structure-of-a-contract.html) or Scilla (https://scilla.readthedocs.io/en/latest/scilla-in-depth.html#structure-of-a-scilla-contract) have.

Maybe, source file layout as well: https://docs.soliditylang.org/en/v0.8.25/layout-of-source-files.html. Or, unite it with the structure of a contract page, as the former lacks much contents to be displayed on it's own.

Besides, the brief explanation of a contract & trait in the https://docs.tact-lang.org/book/types is the only thing we have for them as far as explanations go. And contracts are, well, essential. Their explanation and structure is crucial to define early in the book.

**Comment by novusnota** [comment]
Maybe, source file layout as well: https://docs.soliditylang.org/en/v0.8.25/layout-of-source-files.html

**Comment by anton-trunov** [comment]
Perhaps we can add contract examples with the most common traits like `Deployable` explaining briefly what it means and cross linking to the related docs pages
