### ISSUE TITLE
"next export" is deprecated in favor of "output: export" in next.config.js

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#123]
```
 ⚠ "next export" is deprecated in favor of "output: export" in next.config.js https://nextjs.org/docs/advanced-features/static-html-export
```

**Comment by novusnota** [comment]
Depends on #80, as we can't move to `output: export` yet — I've it tried in the past and it's too limiting compared to our current solution with `next export`. Maybe, once #80 gets resolved I'll return to this choice :)
