### ISSUE TITLE
Example on how to check sender privileges in receivers

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#126]
For instance, we can show an example like this here: https://docs.tact-lang.org/book/receive and cross link to https://docs.tact-lang.org/language/ref/common#require

It can be something really simple, e.g.

```tact
receive(msg: FooBarMsg) {
    require(self.contractOwner == sender(), "Only the owner can increase foobars");
    self.foobars += 1;
}
```

**Comment by novusnota** [comment]
I think that specific examples like this should exist in a Cookbook: #140.
