### ISSUE TITLE
Document `initOf` in the the Book and cross-link it

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#128]
There is a link to https://docs.tact-lang.org/book/statements#initof in https://docs.tact-lang.org/book/composite-types which leads nowhere now.

We should also cross link the description here: https://docs.tact-lang.org/book/send#deploy-contract, possibly also better explaining `initOf` and what goes on there

**Comment by novusnota** [comment]
Depends on #130.
