### ISSUE TITLE
Refactor the structure of Cookbook

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#142]
For instance, sending messages and receiving messages should not be sections with subsections. The Cookbook is a collection of problems and their solutions, the structure should not reflect language constructs, but should be organized using different principles, e.g.
- access control,
- working with randomness,
- working with time,
- working with NFTs,
- ...

**Comment by novusnota** [comment]
I think we should first make 3 major sections of Cookbook: for one, two or many interacting contracts. And for each of the pages, its corresponding link should be prefixed with either `/one-`, `/two-` or `/many-` for clarity and discoverability.

Here's how it will look like in the menu on the left (with exemplary links to those pages/parts):
* Overview `/cookbook`
* One contract
  * Usage examples (ready-made complete contracts, like ones in Map section) `/one-usage-examples`
  * Something else `/one-something-else`
* Two contracts
  * Some topic `/two-some-topic`
  * Something else `/two-something-else`
* Many contracts
  * Some topic `/many-some-topic`
  * Something else `/many-something-else`
  
  And then those "Something else" pages may get organized using different principles, like "Communication" (for sending and receiving messages), "Non-fungible tokens (NFTs)", etc.

**Comment by novusnota** [comment]
Roughing out the structure, looks like this at the moment:

![image](https://github.com/tact-lang/tact-docs/assets/68142933/073f5a0b-f2e1-4599-9fc9-7d39a3545d1c)

Completing this issue is essential for #143 to be made.
