### ISSUE TITLE
Re-write `/book/config` once JSON Schema is added to the tact-lang/tact

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#151]
See:
- https://github.com/tact-lang/tact/issues/178
- https://github.com/tact-lang/tact/pull/194

Additionally, all the config options on other pages (`/book/masterchain`, `/book/debug`, etc.) have to reference this page.

**Comment by VanishMax** [comment]
Here are some points that were misleading to me as a newcomer:
- `parameters` field does not exist. It should be `options`
- The `options` object lacks the documentation for the `external` field
