### ISSUE TITLE
Versioning for tact-docs

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#167]
Basically, I'd like to have a new Tact feature to be documented right after the PR that introduces it is merged, so that after a new Tact release we can quickly deploy the updated tact-docs and not several weeks later. So the `main` branch should not be deployed instantly but should accumulate the stuff for the new Tact release

**Comment by novusnota** [comment]
Agree now, this can be done like you proposed, with simply accumulating stuff and deploying on command.

Later though, it would be nice to have at least two versions of the doc: dev/nightly/etc. for tracking the `main` branch of the Tact and release/etc. one for staying on the latest Tact release (say, 1.2.0 at the moment). In terms of urls, it would look like:
* `https://docs.tact-lang-org/dev/...` — for the development updates directly from `main` branch of docs
* `https://docs.tact-lang-org/...` — for staying on the latest release of Tact

I'll think about it more once Cookbook merges new structure in (#165), and "Language" section becomes "Reference" (#143) :)

**Comment by novusnota** [comment]
Accomplished in the compiler repo — for all the new features we add a badge. And if there are any changes, we make a subheading and place the badge there.
