### ISSUE TITLE
Error in code snippet in pages/book/guides/getting-started/deploy.mdx

### ISSUE THREAD

**Issue by koodl** [tact-lang/tact-docs#171]
Hello!

There is error in code snippet (pages/book/guides/getting-started/deploy.mdx) at line 3:
import { Address, beginCell, storeStateInit, contractAddress, toNano } from 'ton-core';

There must be:
import { Address, beginCell, storeStateInit, contractAddress, toNano } from '@ton/core';

**Comment by anton-trunov** [comment]
Hey @koodl, thanks for reporting the issue. Would you like to open a PR and fix it? Let me mention also that kind of contribution would qualify for a special SBT: https://society.ton.org/contribute-to-tact-compiler
