### ISSUE TITLE
Suggestion for docs.tact-lang.org/book/guides/getting-started/test

### ISSUE THREAD

**Issue by koodl** [tact-lang/tact-docs#172]
Hello!

It would be good for beginners to indicate in paragraph 1 what to enter after running the command: “npm create ton@latest MyProject”.

Example:
<img width="467" alt="Screen Shot 2024-04-05 at 7 02 52 PM" src="https://github.com/tact-lang/tact-docs/assets/94908505/068ca961-a6c0-4812-a73e-7f5ec12e01a1">

**Comment by anton-trunov** [comment]
Alternatively, we could reuse the command mentioned on the landing page:

```
npm create ton -- simple-counter --type tact-counter --contractName SimpleCounter
```

**Comment by novusnota** [comment]
The landing page of docs works as a getting started guide now, since it starts off with creating a new Blueprint project with Tact, then follows up with things to read or explore next, such as the Book, Reference or debugging/testing page
