### ISSUE TITLE
Link "https://www.tact.org/docs/contribute" is broken

### ISSUE THREAD

**Issue by zjor** [tact-lang/tact-docs#18]
Hi, 
I'm trying to get to `docs/contribute` from `https://github.com/tact-lang/tact-docs`
<img width="486" alt="image" src="https://github.com/tact-lang/tact-docs/assets/695809/192405a8-c6cc-4cf9-9024-349af4b18d2f">
but the page is not found.

**Comment by anton-trunov** [comment]
Fixed in https://github.com/tact-lang/tact-docs/commit/03fb275cb103e2af7f20acf33efa9cb879476630
