### ISSUE TITLE
Document `pow` and `pow2` functions

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#190]
Supported both at compile- and run-time since Tact v1.3.0

**Comment by novusnota** [comment]
Yup, and I'm also thinking on having a separate page for all compile-time functions in the Reference (#143):

![image](https://github.com/tact-lang/tact-docs/assets/68142933/e3522446-721b-4358-b915-685810332f82)

**Comment by anton-trunov** [comment]
Yeah, makes sense
