### ISSUE TITLE
`book/functions`  add return value type to the example in the `Extension function` section 

### ISSUE THREAD

**Issue by Vitalii-1996** [tact-lang/tact-docs#196]
The current example is rising the `Type mismatch: Int is not assignable to <void>` error during the compilation.
Condsider adding the type of return value: `extends fun pow(self: Int, c: Int): Int {`

**Comment by anton-trunov** [comment]
Thanks for reporting it @Vitalii-1996!

@novusnota We really need to run all the examples through the Tact typechecker at least (cf #157)
