### ISSUE TITLE
Fix counter example on landing page to return excess TONs to contract caller

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#231]
Let's say the deployer sends 0.05 TONs and calls a simple receiver. They should get the excess back

**Comment by novusnota** [comment]
This would also have to be updated in [ton-org/create-ton](https://github.com/ton-org/create-ton), as this example is taken from there

**Comment by novusnota** [comment]
We may change the receiver from this:

```tact
receive(msg: Add) {
    self.counter += msg.amount;
}
```

To this:

```tact
receive(msg: Add) {
    self.counter += msg.amount;
    self.reply(null); // reply with excessive amount of Toncoin
}
```

But other than that, the deploy seems to be giving the excess back with `DeployOk` message provided by the `@stdlib/deploy` library and `Deployable` trait.
