### ISSUE TITLE
Create a new page for Cells, Slices and Builders

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#234]
They are one of the primitive types in Tact and fundamental to TON Blockchain. We got to have an extended description for them, including construction of Cells with Builders and their parsing via Slices.

Additionally, such page would open way for describing storage modifiers , such as `remaining` (#26) and `bytes32` or `bytes64` (#94).

**Comment by anton-trunov** [comment]
This would be immensely useful!
