### ISSUE TITLE
ref/standard-libraries should have stdlib-reserve page

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#249]
https://docs.tact-lang.org/ref/standard-libraries

**Comment by novusnota** [comment]
Hmm, but there's no `@stdlib/reserve` library: https://github.com/tact-lang/tact/tree/main/stdlib/libs. And the contents of [this](https://github.com/tact-lang/tact/blob/main/stdlib/std/reserve.tact) file is fully described on the Advanced page of the Core libraries: https://docs.tact-lang.org/ref/core-advanced#nativereserve

**Comment by anton-trunov** [comment]
you mean this one? https://github.com/tact-lang/tact/blob/main/stdlib/std/reserve.tact

**Comment by anton-trunov** [comment]
oh yeah, https://github.com/tact-lang/tact/blob/main/stdlib/stdlib.tact#L9

**Comment by anton-trunov** [comment]
I got confused by our own CHANGELOG :)
