### ISSUE TITLE
Tracking issue: Tact v1.4.0

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#255]
- [x] #254
- [x] #252
- [x] #250
- [x] #256
- [x] #269 
- [x] #259
- [x] #267
- [x] #270
- [x] #260
- [x] #273
- [x] #253 
- [x] #276
- [x] #275
- [x] #283

**Comment by anton-trunov** [comment]
Complete

**Comment by novusnota** [comment]
Yay!
