### ISSUE TITLE
Document `as remaining`

### ISSUE THREAD

**Issue by howardpen9** [tact-lang/tact-docs#26]
Related issue: #326

For now, lots of people asking about `forwardPayload: Slice as remaining` when they dealing with Jetton Token.

I think need add more content about this in Tact Docs.

**Comment by novusnota** [comment]
Good suggestion, and to iterate on it, I think that `remaining` keyword should be described in context of Cells and Builders too (see [this](https://github.com/tact-lang/tact/blob/7ed5e05dc0fcbc880f76fe326ea03aae69a3d966/src/types/resolveABITypeRef.ts#L44))

**Comment by howardpen9** [comment]
1

**Comment by foonsun** [comment]
> 1

The remaining is confused.

**Comment by i5possible** [comment]
+1
