### ISSUE TITLE
Specify the hash type of `Cell.hash()` and `Slice.hash()` functions

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#280]
https://docs.ton.org/learn/tvm-instructions/instructions doesn't necessarily help, `HASHCU` and `HASHSU`, which are instructions used in those functions respectively, don't state anything about the nature of the said hash. Just some 256-bit hash ¯\\\_(ツ)\_/¯

Looked at [TON sources](https://github.com/ton-blockchain/ton/blob/5c392e0f2d946877bb79a09ed35068f7b0bd333a/crypto/vm/tonops.cpp#L1210-L1211), but cannot make sense of them yet :)

_As discussed in [Tact chat](https://t.me/tactlang/33962)_

**Comment by anton-trunov** [comment]
> https://docs.ton.org/learn/tvm-instructions/instructions doesn't necessarily help

Could you please open an issue about that in the ton-docs repo and link it here?

**Comment by novusnota** [comment]
https://github.com/ton-community/ton-docs/issues/645

**Comment by anton-trunov** [comment]
https://github.com/tonstack/ton3-core/blob/main/src/boc/cell.ts#L396

**Comment by anton-trunov** [comment]
and also this https://github.com/ton-org/ton-core/blob/main/src/boc/cell/wonderCalculator.ts#L21
