### ISSUE TITLE
Fix struct and messages optional fields description

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#306]
```
age: Int?;                 // optional field
```

this is misleading description, which implies `age` can be omitted, which is not true.

So, the following snippet copied from the docs does not compile:
```
init() {
        self.params = Params{
            point: Point{
                x: 4,
                y: 2,
            },
        };
    }
```

precisely because it is missing the `age` field.

**Comment by novusnota** [comment]
Is this related to https://github.com/tact-lang/tact/issues/540? I think that specifying an optional type for a field (say, `Int?`) should implicitly set the default value of that field to `null`, and adding default values in general should lift the requirement on providing values for those fields upon instantiation.

But as of now, constant evaluator requires all fields to be present, even `name` from the example in the docs/above!

**Comment by anton-trunov** [comment]
Good catch! I'll fix this in Tact

**Comment by novusnota** [comment]
That said, I want to enhance the description there just a tad, so I'll re-open this issue and send a small PR for it :)
