### ISSUE TITLE
Clarify `require` does not throw string errors just exit codes and where to look for the corresponding exit code

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#310]
It a common misconception that `ref/core-debug#require` actually throws a string. We need to explain this better and also point to where to look for the corresponding exit code. (Incidentally, the editor should do that for the user when they hover the error message)

**Comment by novusnota** [comment]
`require()` produces its exit codes according to the following algorithm:

```ts
sha256_sync(errorMessageString).readUInt32BE(0) % 63000) + 1000
```

Source: https://github.com/tact-lang/tact/blob/99c30636d41b76a9a5181790c9bb326116d0725a/src/types/resolveErrors.ts#L19
