### ISSUE TITLE
Lack of valid examples for Ownable

### ISSUE THREAD

**Issue by Mr-Dm1try** [tact-lang/tact-docs#316]
I've noticed that [Access control](https://docs.tact-lang.org/cookbook/access) page has no valid examples of how to use Ownable trait. 

Like instead calling existing function `self.requireOwner()` it provides example of `require(self.owner == sender(), "message");`

**Comment by Mr-Dm1try** [comment]
https://github.com/tact-lang/tact-docs/pull/317

**Comment by novusnota** [comment]
Nice catch!

**Comment by novusnota** [comment]
Resolved in #317 by @Mr-Dm1try
