### ISSUE TITLE
dump() does not work for Address

### ISSUE THREAD

**Issue by sergeipalii** [tact-lang/tact-docs#318]
reproduce:
yarn create ton simple-counter --type tact-counter --contractName SimpleCounter
in contracts/simple_counter.tact add dump to:
    receive(msg: Add) {
        self.counter += msg.amount;
        dump(1);
        dump(myAddress());
        dump(2);
        // Notify the caller that the receiver was executed and forward remaining value back
        self.notify("Cashback".asComment());
    }

    only first dump works
    #DEBUG#: [DEBUG] File contracts/simple_counter.tact:19:9
    #DEBUG#: 1
    
    test failed
    send Add results in exitCode -14
    
     {
        lt: 7000000n,
        now: 1720946393,
        outMessagesCount: 0,
        oldStatus: 'active',
        endStatus: 'active',
        totalFees: 50000000n,
        from: EQBGhqLAZseEqRXz4ByFPTGV7SVMlI4hrbs-Sps_Xzx01x8G,
        to: EQDvermQQzolmlXr9SgsLNN0ZbbmzU-oY73muFdQsgc7ovSA,
        on: EQDvermQQzolmlXr9SgsLNN0ZbbmzU-oY73muFdQsgc7ovSA,
        value: 50000000n,
        body: x{8B341822000000000000000000000041},
        inMessageBounced: false,
        inMessageBounceable: true,
        op: 2335447074,
        initData: undefined,
        initCode: undefined,
        deploy: false,
        aborted: true,
        destroyed: false,
        exitCode: -14,
        actionResultCode: undefined,
        success: false
      }

**Comment by anton-trunov** [comment]
exit code -14 means you send not enough gas and debugging consumes gas, actually a lot of it, so just increase the amount of gas to something like `0.5` tons and everything will be working
