### ISSUE TITLE
The URL for "Edit this page" is wrong. 

### ISSUE THREAD

**Issue by howardpen9** [tact-lang/tact-docs#32]
- The URL for "Edit this page" is wrong. 
- Will direct to https://github.com/shuding/nextra/pages/language/ref/advanced.mdx once I click it.

![image](https://user-images.githubusercontent.com/36764495/231201729-723c82e1-7766-4cba-b5ad-6db2e04d1dfe.png)

**Comment by howardpen9** [comment]
![image](https://github.com/tact-lang/tact-docs/assets/36764495/12307749-491c-4083-935a-dd7425121021)

**Comment by anton-trunov** [comment]
Thanks! Should be fixed now
