### ISSUE TITLE
Fungible tokens (jettons) in Cookbook

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#321]
Description in https://docs.tact-lang.org/cookbook/jettons is missing. It should contain recipes on how to work with existing jettons in Tact. (Note this is **not** about implementing jettons in Tact).

@a-bahdanau Would also be nice to have an example for TON/USDT.

**Comment by a-bahdanau** [comment]
Я возьмусь

**Comment by howardpen9** [comment]
Would love to take a reference a bit :

https://github.com/howardpen9/jetton-implementation-in-tact

**Comment by a-bahdanau** [comment]
@anton-trunov what do you mean by TON? Some toncoin wrapper?

**Comment by anton-trunov** [comment]
@a-bahdanau `TON/USDT` is USDT on top of TON :) Sorry, in this context this must be confusing. I could have just said USDT
