### ISSUE TITLE
Make exit codes link more visible

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#328]
We should move it from the bottom of the `Going places` section in the table of contents somewhere else. Maybe `Fundamentals of Tact`

**Comment by novusnota** [comment]
Interesting, but maybe we just have to link them better from other pages and/or tell users about the `Ctrl + K` search feature right on the starting page of the docs and on the main overview pages of each section (Book, Cookbook, etc.)

**Comment by anton-trunov** [comment]
It's one of the most fundamental things actually. It's an important part of the language semantics and questions about this part are really frequent

**Comment by novusnota** [comment]
I just realized how the docs can make a smooth transition from the contracts in `Fundamentals of Tact` to them (in #106), and now I'm fully on board with moving exit codes around :)
