### ISSUE TITLE
Emphasize integer range in explanation of repeat statement

### ISSUE THREAD

**Issue by jeshecdom** [tact-lang/tact-docs#347]
In the repeat statement explanation:

https://docs.tact-lang.org/book/statements#repeat-loop

The sentence "Number of repetitions must be a non-negative 32-bit Int", could be understood as saying that it is a 32-bit unsigned integer. So, it may be better to include the allowed integer range. For example, as:

Number of repetitions must be a non-negative 32-bit Int, i.e., a number `x` such that `0 <= x <= 2^31 - 1`.

Or simply:

Number of repetitions must be a non-negative integer (`>= 0`) smaller or equal than `2^31 - 1`.

**Comment by novusnota** [comment]
Not quite, range check is only thrown when the number is greater than $2^31 - 1$. If the number is less than zero and even as low as $-2^256$, there is no exception

**Comment by jeshecdom** [comment]
So, I guess that executing the repeat a negative number of times is equivalent to executing it 0 times?

**Comment by novusnota** [comment]
@jeshecdom exactly so. I'll clarify that in a PR in a moment
