### ISSUE TITLE
book/maps has incorrect map type

### ISSUE THREAD

**Issue by a-bahdanau** [tact-lang/tact-docs#352]
https://github.com/tact-lang/tact-docs/blob/d6ec58ee3180b50f2f89293019e3c7985d6603da/pages/book/maps.mdx?plain=1#L83

Invalid types provided. Map is <Int, Int>, but type String? was provided to variable. Moreover, the page does not mention `String` is a valid map value type.

Also, in on the same page:
```
arr: map<Int, Int>; // "array" of String values as a map
```

**Comment by a-bahdanau** [comment]
@anton-trunov hey, you have just edited my description and added `Moreover, the page does not mention String is a valid map value type.`. Seem like tact does not support String as map type yet

**Comment by anton-trunov** [comment]
@a-bahdanau Right, `String` is not supported, although the typechecker does not always report it: https://github.com/tact-lang/tact/issues/701
