### ISSUE TITLE
Correct description of the `repeat` loop boundaries

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#379]
The exit code 5 will be thrown when the integer is out of its 257-bit signed bounds, NOT when the integer is bigger than $2^{31} - 1$

**Comment by anton-trunov** [comment]
Is there a reference backing this?

**Comment by novusnota** [comment]
The tests in https://github.com/tact-lang/tact/pull/766

**Comment by anton-trunov** [comment]
It looks like we need to open an issue in ton-docs then: https://docs.ton.org/develop/func/statements#repeat-loop

> If the number of times is less than -2^31 or greater than 2^31 - 1, range check exception is thrown.

**Comment by novusnota** [comment]
> It looks like we need to open an issue in ton-docs then: https://docs.ton.org/develop/func/statements#repeat-loop
> 
> > If the number of times is less than -2^31 or greater than 2^31 - 1, range check exception is thrown.

Yes, the is no error for numbers less than -2^31. But there is for greater — I just made an whoopsie and looked at a different test, so this issue is incorrect :)
