### ISSUE TITLE
random() range seems invalid

### ISSUE THREAD

**Issue by k0marov** [tact-lang/tact-docs#38]
At https://docs.tact-lang.org/language/ref/random it is specified that random() provides a number with the range from <= x <= to. 
In my smartcontract it was not working as intented, so I tried to check it manually, and it looks like that actually random() outputs numbers in the range from <= x < to. That is, second argument is not included. 
Probably, the docs are not correct.

**Comment by anton-trunov** [comment]
Thanks! Should be fixed now
