### ISSUE TITLE
Document how to debug your contract and dump variables

### ISSUE THREAD

**Issue by talkol** [tact-lang/tact-docs#4]
Add one section about debugging contracts in general

Add the `dump` function to the reference of static available functions

**Comment by ex3ndr** [comment]
https://docs.tact-lang.org/language/ref/common#dump
https://docs.tact-lang.org/language/guides/debug

**Comment by anton-trunov** [comment]
The Tact Telegram chat interactions show people still have some issues with using the `dump` function, for instance they expect adding `dump` to their contracts and running tests would automatically log everything to the console. We should clarify the workflow in https://docs.tact-lang.org/book/debug#printing-out-debug-data

**Comment by novusnota** [comment]
Depends on #125 and #112.

**Comment by anton-trunov** [comment]
One more issue our users experience with `dump`: how to use it with Blueprint.

> When creating a new blueprint project I don't have a default tact.config.json file. I created a file in the project root, but it doesn't work

**Comment by novusnota** [comment]
> One more issue our users experience with `dump`: how to use it with Blueprint.
> 
> > When creating a new blueprint project I don't have a default tact.config.json file. I created a file in the project root, but it doesn't work

Yes, the answer is simple, but undocumented yet in our docs (and tough to find in Blueprint/Sandbox):

![image](https://github.com/tact-lang/tact-docs/assets/68142933/2171e83b-f037-42fc-b02f-ec0ed0a9f33b)
