### ISSUE TITLE
Add link checking to CI (and git hooks)

### ISSUE THREAD

**Issue by novusnota** [tact-lang/tact-docs#65]
1. All the links in docs should be automatically checked each week for the valid response of the servers (200 or 301/302).
2. Optional: Add a pre-commit or pre-push hook to check the validity of the links.

**Comment by anton-trunov** [comment]
Corresponding Tact issue: https://github.com/tact-lang/tact/issues/755 and PR to misti: https://github.com/nowarp/misti/pull/110

**Comment by anton-trunov** [comment]
> Optional: Add a pre-commit or pre-push hook to check the validity of the links.

Instead of git hooks we might want to use Husky

**Comment by novusnota** [comment]
Resolved in https://github.com/tact-lang/tact/pull/880, the `build` script automatically checks all the internal links via a Starlight plugin for it.

If there would be need for checking the external links (i.e. to TON Docs), the new issue may be opened in the Tact repo
