### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by anton-trunov** [tact-lang/tact-docs#84]
error 404 for:
-  https://docs.tact-lang.org/ecosystem/tools
- https://docs.tact-lang.org/book/guides
- https://docs.tact-lang.org/book/cs

**Comment by anton-trunov** [comment]
The recent refactoring in #81 broke the links in tact-by-example, see issue https://github.com/tact-lang/tact-by-example/issues/34

**Comment by novusnota** [comment]
> The recent refactoring in #81 broke the links in tact-by-example, see issue [tact-lang/tact-by-example#34](https://github.com/tact-lang/tact-by-example/issues/34)

Split this issue in two and moved that last part in #86.
Now, this issue (#84) is going to be resolved in a quick fix in 10-15 minutes to make current docs fully functional. Later today I'll resolve #86 too!
